name: Deploy static site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "." # default value when not using subfolders

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BUILD_PATH }}
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # Setup Node
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # Setup Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # Build landing page
      - name: Build frontend
        run: |
          corepack enable
          pnpm install
          pnpm build --base /hymnal/
      # Populate HTML template with JSON
      - name: Generate static content
        run: |
          python -m venv .venv
          . ./.venv/bin/activate
          pip install .
          python src/hymnal/main.py
          deactivate
          git clone --depth 1 "https://github.com/hakimel/reveal.js.git" dist/lib/reveal.js
      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      # Upload static page
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.BUILD_PATH }}/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
