name: Deploy static site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "." # default value when not using subfolders

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BUILD_PATH }}
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # Enable pNpM
      - name: Enable pNpM
        run: corepack enable
      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      # Install dependencies
      - name: Install dependencies
        run: pnpm install
      # Build static page
      - name: Build static pages
        run: pnpm build --base /hymnal/
      # Setup Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # Install & configure Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      # Install dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --only main --no-root
      # Post build steps
      - name: Post build step
        run: |
          source .venv/bin/activate
          python hymnal/converter.py
          git clone --depth 1 "https://github.com/hakimel/reveal.js.git" dist/lib/reveal.js
      # Upload static page
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.BUILD_PATH }}/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
